[package]
name = "serde-kdl-macro"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for serde-kdl"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kdl-org/serde-kdl"
documentation = "https://docs.rs/serde-kdl-macro"
keywords = ["kdl", "serde", "serialization", "config", "parser", "macro"]
categories = ["encoding", "parser-implementations", "config"]
authors = ["Gaëtan Schwartz"]

[features]
default = ["ide-hints"]
ide-hints = []

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
kdl = "6.5"
derive-syn-parse = { version = "0.2.0", features = ["full"] }
rstest = "0.26.1"
trybuild = { version = "1.0.114", features = ["diff"] }
pretty_assertions = "1.4.1"
seq-macro = "0.3.6"

[dev-dependencies]
insta = "1.44.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
