[workspace]
members = [".", "serde-kdl-macro"]

[package]
name = "serde-kdl"
version = "0.1.0"
edition = "2021"
description = "Serde serialization and deserialization for KDL (Kindly Document Language)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kdl-org/serde-kdl"
documentation = "https://docs.rs/serde-kdl"
keywords = ["kdl", "serde", "serialization", "config", "parser"]
categories = ["encoding", "parser-implementations", "config"]
authors = ["Gaëtan Schwartz"]

[features]
default = ["bytes"]
bytes = []
macros = ["dep:serde-kdl-macro"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
kdl = "4.7"
thiserror = "1.0"
serde-kdl-macro = { path = "serde-kdl-macro", optional = true }
rstest = "0.18"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
rstest = "0.18"
rand = "0.8"
